sources:
  - name: "source"
    database: |
        {%- set target_name = target.name.lower() -%}
        {%- if target_name in ['prod'] -%} DB_DBT_LLENOIR_PROD
        {%- else -%} LLENOIR_DB
        {%- endif -%}
    tables:
      - name: restaurants
      - name: dishes
      - name: fuzzy_orders
      - name: orders
        columns:
          - name: identifier
            tests:
              - unique:
                  config:
                    severity: warn
          - name: amount
            tests:
              - is_positive
      - name: |
          {%- set target_name = target.name.lower() -%}
          {%- if target_name in ['prod'] -%} STAGE_DBT_LLENOIR_PROD
          {%- else -%} LLENOIR_DB
          {%- endif -%}
      - name: stream_orders

      

       
    